library(tidyr)

features.values <- read.table("output//features_values.tsv", header = TRUE, sep = "\t")
features.values$id <- rep(1:(nrow(features.values)/3), each=3)
features.values.wide <- spread(features.values, featurename, featurevalue)
hist(features.values.wide$baselinetopscore)
hist(features.values.wide$fieldlikelihood)
hist(features.values.wide$bigramcfratio[features.values.wide$ngramtype != "unigram"])
min(features.values.wide$fieldlikelihood[features.values.wide$fieldlikelihood != -Inf])
max(features.values.wide$fieldlikelihood)
min(features.values.wide$baselinetopscore[features.values.wide$baselinetopscore != -Inf])
max(features.values.wide$baselinetopscore)
min(features.values.wide$bigramcfratio[features.values.wide$bigramcfratio != -Inf & features.values.wide$ngramtype != "unigram"])
max(features.values.wide$bigramcfratio[features.values.wide$ngramtype != "unigram"])
