library(tidyr)

features.values <- read.table("output//features_values.tsv", header = TRUE, sep = "\t")
features.values <- unique(features.values)
features.values.wide <- spread(features.values, featurename, featurevalue)
hist(features.values.wide$baselinetopscore)
hist(features.values.wide$fieldlikelihood)
hist(features.values.wide$bigramcfratio[features.values.wide$ngramtype != "unigram"])
print(min(features.values.wide$fieldlikelihood[features.values.wide$fieldlikelihood != -Inf]))
print(max(features.values.wide$fieldlikelihood))
print(min(features.values.wide$baselinetopscore[features.values.wide$baselinetopscore != -Inf]))
print(max(features.values.wide$baselinetopscore))
print(min(features.values.wide$bigramcfratio[features.values.wide$bigramcfratio != -Inf & features.values.wide$ngramtype != "unigram"]))
print(max(features.values.wide$bigramcfratio[features.values.wide$ngramtype != "unigram"]))

importance.features.values <- read.table("output//importance_features_values.tsv", header = TRUE, sep = "\t")
importance.features.values <- unique(importance.features.values)
importance.features.values.wide <- spread(importance.features.values, featurename, featurevalue)
hist(importance.features.values.wide$collectiontf)
print(min(importance.features.values.wide$collectiontf[importance.features.values.wide$collectiontf != -Inf]))
print(max(importance.features.values.wide$collectiontf))
